version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: development
    command: yarn start:dev api
    env_file:
      - ./api/.env
    restart: always
    depends_on:
      - db_mongo
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - '3000:3000'
  db_mongo:
    container_name: db_mongo
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/data/db'
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: development
    command: yarn start:dev app
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'

volumes:
  mongodb_data:
    driver: local
