version: '3.8'

services:
  api:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: yarn start app
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'

